- package-lock.json
- package.json
- tailwind.config.js
* apexcharts, daisyui 패키지 설치
* tailwind config에 plugin 설정 추가 (daisyUI)
> chore: apexcharts, daisyui 패키지 설치

- src/pages/Test.tsx
> style: 코드 수정

- src/components/layout/Footer.tsx
- src/components/layout/Header.tsx
- src/components/layout/Logo.tsx
> fix: layout 부분 링크 추가, z-index 적용, ui 수정

- src/components/common/LoadingIndicator.tsx
> feat: 로딩인디케이터 컴포넌트 추가

- src/components/layout/Footer.tsx
- src/components/layout/Header.tsx
header의 checked -> defaultChecked로 변경
footer 링크 복사 추가 및 깃허브 링크 연결
> fix: 레이아웃 오류 수정, 링크 추가

- src/components/test/HashTag.tsx
- src/components/test/RelationType.tsx
- src/components/test/TypePercentageBar.tsx
- src/components/test/TypePercentageBars.tsx
- src/constants/bgColor.ts
- src/interfaces/color.ts
- src/interfaces/index.ts
- src/interfaces/resMbti.ts
- src/pages/test/TestResult.tsx
1. mbti 결과 조회 api로 데이터 받아온 후  알맞게 데이터 바인딩
2. interface 폴더에 resMbti.ts + color.ts 파일 추가
3. constants 폴더에 bgColor.ts를 object에서 array 형태로 변경 -> filter함수 사용하기위해
> feat: mbti 타입에 맞는 데이터 바인딩

- src/components/board/BulletinCardModal.tsx
- src/components/board/ChangeMbtiBtn.tsx
- src/components/board/HeartBtn.tsx
- src/components/board/MbtiColorChip.tsx
- src/components/common/MbtiTypesModal.tsx
- src/pages/board/BulletinBoard.tsx
- src/pages/board/BulletinDetail.tsx
- Board 관련 파일 작업 내용을 원상복구했습니다.
> fix: Board 파일 업데이트

- src/components/common/Character.tsx
- src/interfaces/index.ts
- src/interfaces/stats.ts
- src/pages/stats/Stats.tsx
> hotfix: 누락사항 추가

- src/api/index.ts
> hotfix: env 수정

- src/api/index.ts
> fix: api endpoint 수정

- src/api/index.ts
> fix: api url 수정

- src/pages/stats/StatsMbti.tsx
1. MBTI 선택 모달 적용 및 라우팅 처리
2. 로딩 컴포넌트 적용
3. API 응답 데이터가 null인 경우를 고려해 조건부 렌더링 로직 추가
> MBTI별 통계페이지 작업

- src/interfaces/question.ts
> fix: 불필요한 코드 삭제

- src/pages/stats/StatsMbti.tsx
* API 응답 객체 변경에 따른 데이터 가공 함수 추가
* 코드 리팩토링
> MBTI별 통계 페이지 수정 작업

- public/index.html
- src/components/test/TestCard.tsx
- 링크 섬네일 미노출 해결
- 테스트카드 색상 이슈 해결
> fix: 이슈 해결

- public/index.html
- public/manifest.json
- src/components/test/TestCard.tsx
- 아이콘 이미지 및 디스코드 섬네일 이슈 수정
- hover 시 텍스트 컬러 변경 이슈 수정
> fix: 이슈 수정

- public/index.html
- 디스코드 섬네일 표시를 위한 twitter meta tag 추가
> fix: twitter meta tag 추가

- src/pages/stats/StatsMbti.tsx
* 담벼락 바로가기 버튼 링크 수정
* MBTI 답변 요소 추가
* MBTI 통계페이지의 footer가 뜨는 현상 해결
* Footer 분리
* 코드 복잡도 개선 작업
> MBTI별 통계페이지 수정 작업

- src/pages/stats/StatsMbti.tsx
변경 사항
- component 경로 수정
변경 사유
- 폴더 경로가 달라 에러 발생. 따라서 경로 수정 진행하였음
> ChangeMbtiBtn import 경로 수정

- .eslintrc.json
- .prettierrc.json
- babel-plugin-macros.config.js
- craco.config.js
- craco.config.ts
- package-lock.json
- package.json
- tailwind.config.js
변경사항
- eslint 설정 변경
- prettier 설정 변경 (tadWidth 2) / 파일명 변경
- config 파일 es모듈 형식 변경 (craco, babel-plugin-macros, tailwind)
변경 사유
- require 사용시 eslint 오류 발생하여 es모듈로 설정 변경
- eslint, prettier 연동 재확인
> eslint, prettier 

- src/pages/board/BulletinBoard.tsx
변경사항
- board 파일 import 경로 수정 및 중복 코드 제거
변경 사유
- 충돌 병합 과정에서 중복 코드 제거를 하지 않아 에러 발생. 따라서 제거하였음
> fix: boardPost import 경로 수정 및 충돌 병합

- src/components/layout/Footer/Footer.tsx
- Footer 파일 url 공유 코드 web share API로 변경 작업
- web share API 로 변경을 위한 테스트 작업
> fix: Footer web share API 테스트

- src/components/board/BoardPost/BoardPost.styles.ts
- src/components/board/BoardPost/BoardPost.tsx
- src/components/common/ShareLink.tsx
###변경 사항
- BoardPost 파일 PassWord 기능 추가 
- ShareLink Share open api 코드 수정
###변경 사유
- BoardPost 페이지의 PassWord 기능 추가
- ShareLink에 Share open api 호환 안되는 조건의 url 코드 수정
> feat: BoardPost password 기능 추가 및 ShareLink 코드수정

- src/pages/test/test/Test.tsx
> 변경사항
- 문항 정보 표시하는 로직 리팩토링
- 답변 위치 랜덤 배치
> 변경사유
- 인덱스에 따라 성향을 배치했는데, 문항 배치가 랜덤이 됨에 따라 로직 수정
- 답변 위치를 랜덤으로 배치하여 사용자가 더 유연하게 생각하여 답변을 체크할 수 있도록 수정
> refactor: 문항 정보 표시 로직 리팩토링 및 답변 위치 랜덤 배치

- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.styles.ts
- src/components/comment/CommentPost.styles.ts
- src/components/comment/CommentPost.tsx
- src/components/common/CommentCharacter.tsx
- src/pages/board/BulletinBoard.tsx
- Comment 파일 character 색상 선택 기능 추가
- Comment 파일 character 프로필 색상 선택 후 반영
> feat: Comment Character 색상 선택 기능 추가

- src/components/board/BulletinCard/BulletinCard.styles.ts
- src/hooks/useInfinitiScroll.tsx
- src/pages/board/BulletinBoard.tsx
변경사항
담벼락 페이지 무한 스크롤 적용
변경사유
기능 추가 (hook 분리, 적용 및 스타일 변경)
> refactor: 담벼락 무한 스크롤 적용

- package-lock.json
- package.json
- src/index.tsx
* react-query, devtools 패키지 설치
* `index.tsx`에 react query 관련 코드 추가
* react-query 도입에 따른 환경 설정 필요
> 리액트 쿼리 환경 설정

- src/pages/stats/Stats.tsx
- src/pages/stats/statsMbti/StatsMbti.tsx
* 전체 통계 페이지, MBTI별 통계 페이지에 React Query 적용
* React Query 도입에 따른 적용 필요
> 통계페이지 React Query 적용

- package-lock.json
- package.json
* 리액트쿼리 V4 버전대로 다운그레이드
* V5가 아직 정식출시되지 않았음.
> 리액트 쿼리 다운그레이드

- src/@types/Question.ts
- src/@types/index.ts
- src/components/test/loading/Loading.tsx
- src/pages/test/TestResult/TestResult.tsx
- src/pages/test/test/Test.tsx
> 변경사항
- test, testResult, Loading에서 api 호출부 react-query 적용
> 변경사유
- react-query migration
> test 페이지 react query 적용

- src/@types/Comment.ts
- src/components/board/BoardPost/BoardPost.tsx
- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.tsx
- src/components/comment/CommentPost.tsx
- src/pages/board/card/CardDetail.tsx
- comment 댓글 추가 작업 및 삭제 기능 작업
- comment 추가 및 삭제 기능을 위한 작업
> fix: comment delete 기능 추가및 comment 작업

- src/@types/Comment.ts
- src/@types/index.ts
- src/components/board/BoardPost/BoardPost.styles.ts
- src/components/board/Button/HeartBtn/CommentHeartBtn.tsx
- src/components/comment/CommentContent.styles.ts
- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.styles.ts
- src/components/comment/CommentEdit.tsx
- src/components/comment/CommentEditPassWord.tsx
- src/components/comment/CommentPost.tsx
- src/components/common/MbtiTypesModal/MbtiTypesModal.styles.ts
- Comment CRUD 작업
- Comment 대댓글 작성 작업
- Comment 기능구현을 위한 작업
> fix: Comment 작업 및 대댓글post작업

- src/@types/Comment.ts
- src/components/comment/CommentContent.tsx
> 변경사항
- 댓글의 댓글(대댓글) 표시 및 기능 구현
> 변경사유
- 대댓글 표시 위함
> fix: 댓글 계층형 구현

- src/@types/Board.ts
- src/@types/Comment.ts
- src/components/board/BoardPost/BoardPost.styles.ts
- src/components/board/BulletinCard/BulletinCard.tsx
- src/components/board/Button/CommentBtn/CommentBtn.styles.ts
- src/components/board/Button/CommentBtn/CommentBtn.tsx
- src/components/comment/CommentContent.styles.ts
- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.tsx
- src/components/comment/CommentEditPassWord.tsx
- src/components/comment/CommentPost.styles.ts
- src/components/comment/CommentPost.tsx
- src/index.css
- src/pages/board/card/CardDetail.styles.ts
- src/pages/board/card/CardDetail.tsx
- Comment 작업 마무리(Comment 수정, 카운트, 글자 수 , 스크롤 ui 제거)
- Reply 작업 마무리
- Comment, Reply 기능 구현을 위한 작업
- CommentBtn 컴포넌트를 만들어 댓글 조회 api를 사용하였는데 의도하지 않을때도 조회가 될때 오류가 생김
> fix: Comment, Reply 기능 구현 작업

- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.tsx
- src/components/comment/CommentPost.tsx
댓글 입력 후 enter 키 입력하면 등록될 수 있도록 이벤트 추가
사실 모바일 우선이기 때문에 해당 기능은 필요 없을 수 있으나
웹에서 테스트 시 해당 이슈가 있기에 추가했음.
> fix: 댓글 입력 후 enter시 등록 요청

- src/pages/board/BulletinBoard.tsx
> fix: 게시글 작성 시 재조회 오류 해결

- src/pages/board/BulletinBoard.tsx
> fix: 무한스크롤 isloading state 추가

- src/components/board/Button/HeartBtn/CommentHeartBtn.tsx
- src/components/comment/CommentContent.tsx
- src/components/comment/CommentEdit.tsx
- src/components/comment/CommentEditPassWord.tsx
- src/components/common/ShareLink.tsx
- src/pages/board/BulletinBoard.tsx
- src/pages/board/card/CardDetail.tsx
> console 제거 및 loading 컴포넌트 추가

- src/pages/board/BulletinBoard.tsx
> fix: console 제거, loading 제거
